### ISSUE TITLE
7_Restropective

### ISSUE THREAD

**Issue by hadoan149** [lab-brussels-1/group5#22]
### Where can we help others moving forwards?

---

**Comment by hadoan149** [comment]
- [ ] Gather what we learn
- [ ] Create a `Restrospective.md `to put them all together

**Comment by hadoan149** [comment]
## Group 5

### What was not clear, where did we get stuck?

We did not start with the planning, therefore, communication was hard and it took way more time as we have to explain it to those who couldn't make it to the meetings.

### What was clear, what did we master?
- creating the md files
- always `git pull `before make any changes
- knowing others' schedules and working styles
- some `html `and `css` skills


### Where can we still use some help?
- how to work collaboratively (still the biggest problem for us)

### Where can we help others moving forwards?
- those who are more experienced or available more should set some time off to help others
---

## The Course

### What can there be more of?

### What can there be less of?

### What material were most helpful (from HYF or elsewhere)?
- Youtube videos

### What HYF material was least helpful?
- Nothing, everything was well used
### Any suggestions for future classes?
- would be nice to make the team more diverse based on team members' background. We can complement each other this way
- perhaps, when explaining the deliverables (especially in this case), rather than focusing on the actual deliverables, more attention should be given to the prioritized tasks e.g. planning and communication. We were led immediately to the technical steps rather than planning. Something for us to learn too of course

**Comment by MahaLubbad** [comment]
## Group 5

### What was not clear, where did we get stuck?

Sometime we were confused where we can find the files 


### What was clear, what did we master?



### Where can we still use some help?
Solving some lintng conflicts 


### Where can we help others moving forwards?
Working in local machine , creating new branch and other steps until creating pull Requests and reviewing the others PR and merging it 

---

## The Course

### What can there be more of?
All the subjects have multiple choices 
### What can there be less of?
All the subjects have multiple choices 
### What material were most helpful (from HYF or elsewhere)?

- [Traversy - HTML Crash Course For Absolute Beginners](https://www.youtube.com/watch?v=UB1O30fR-EE)
- [Traversy - CSS Crash Course For Absolute Beginners](https://www.youtube.com/watch?v=yfoY53QXEnI)
- 
### What HYF material was least helpful?

### Any suggestions for future classes?

**Comment by EliasMlopez99** [comment]
## Group 5

### What was not clear, where did we get stuck?
I think we had a lot of trouble when we were changing files and git pushing. However from this mistake we have learned that we have plan very well our steps in order to prevent this kind of errors 


### What was clear, what did we master?
- Planning as team each task, how and when to be performed
- Using css/html and `npm` commands to check our codificaction
- We also learned the base for creating a project, and what we should take in count when we want to do a project


### Where can we still use some help?

### Where can we help others moving forwards?
I had a lot of help from my teammates, i was not aware if what i needed to do, telling someone what he/she has to do pointing out from where he can get certain information or base his/her work can be very useful
---

## The Course

### What can there be more of?
Everything is fine,  i have nothing to say
### What can there be less of?
Less reading more practice, i think that Web developing can be tough if you do not know the concepts, but if you want to learn the concepts you have to put it in practice so you make mistakes and you learn from them and by consequence you will consolidate the knowledge 

### What material were most helpful (from HYF or elsewhere)?
Youtube videos have helped me
### What HYF material was least helpful?
Nothing is less helpful so far, all the info that you have is enough and get you right to the point

### Any suggestions for future classes?
Just to take us more into practice, otherwise everything else is perfect

**Comment by andriivam** [comment]
## Group 5

### What was not clear, where did we get stuck?
I thin we had some problem at the begging as we didn't know well how to create planing documents and how to use them properly.

### What was clear, what did we master?
How to resolve the conflicts and run all the lint, css and HTML checks.
### Where can we still use some help?
How to work in the group more effectively and correctly.
### Where can we help others moving forwards?

---

## The Course

### What can there be more of?
I would like to have more practical tasks as already understand the way to learn coding is daily workout.
### What can there be less of?
On my opinion  very good comment left my group mate Elias so I don't have nothing extra to say.
### What material were most helpful (from HYF or elsewhere)?
For me really helps a lot live meeting with coaches in zoom and video like @Tamer did.
### What HYF material was least helpful?
The all material was great and really helpful. just need to learn how to use that most effectively.
### Any suggestions for future classes?
As for me would be great if each team will have person who has some background    as in some difficult situation it can help for the group work better. Plus, during the group project other members can learn a lot from this person.

**Comment by SWAPNACHEMBOTH** [comment]
What was not clear, where did we get stuck?
I think we got confused at the beginning and did not start with the planning. Also, we got into many communication issues.

What was clear, what did we master?
- Planning
- Creating md files
- Npm commands
- Git pull before any changes

Where can we still use some help?
HTML & CSS

Where can we help others moving forwards?
Took lot of help from teammates. Also taking time to understand.

The Course
What can there be more of?
As a beginner, i felt enough content to check.

What can there be less of?
As the content is more to read, sometimes it is confusing as well.

What material were most helpful (from HYF or elsewhere)?
HYF & Google

What HYF material was least helpful?
I felt everything was helpful

Any suggestions for future classes?
For me its good, however lot of practices to be carried out.
